### PR TITLE
add MAKEFILE and update README

### PR DESCRIPTION
**Pull request by mltbnz**
## 📲 What

Add a Makefile to setup new devs easier.

## 🤔 Why

To add the tools needed for this repo the README was lacking a setup step.

### CODE REVIEW

**Comment by lennet** [comment]
Can you elaborate why it's needed? The tools are shipped with the repo and the current master should contain a formatted version. I would prefer a setup where no manual setup steps are needed and a contributor can just open the project in Xcode

**Comment by mltbnz** [comment]
where is swiftformat for example shipped with the repo? Must have missed that.
If so why is it shipped with the repo?

**Comment by lennet** [comment]
in the [bin folder](https://github.com/criticalmaps/criticalmaps-ios/tree/master/bin). The only tool we are not shipping with the repo is fastlane but that's also not required on the machine

**Comment by mltbnz** [comment]
So it is there as a binary that is updated with the github action on a weekly basis?

**Comment by lennet** [comment]
yes

**Comment by mltbnz** [comment]
> yes

**Comment by mltbnz** [comment]
But I guess it didn’t make much sense then.
I wasn’t aware there are binaries we keep in the repo or I forgot about it probably.

Is the Format build Phase actually using it?

I think it would be cool to have 3rd dependencies in the app via SPM and then use ` swift run` but I think for that the  critical maps kit would needed to be extracted first

**Comment by mltbnz** [comment]
Postponed until a nicer solution is at hand

**Pull request closed without merging**
