### PR TITLE
Twitter cell layout fix

### LINKED ISSUE #48: Chat & Twitter cell paddings
Chat and Twitter cells don't have the right paddings / margins and font sizes / line height. Defined in [sketch](https://github.com/criticalmaps/criticalmaps-design/tree/master/ios).

### Chat:

*Is:*

*Should:*

*Specs:*

> Padding: 16px
> Date: 15px / 16px - Bold #262626
> Margin between date and message: 4px
> Message: 17px / 24px - Regular #45474D

### Twitter:

*Is:*

*Should:*

*Specs:*

> Padding: 16px
> Avatar: 40x40px - Inner border: 1px rgba(55,64,82,0.18)
> Margin between avatar and text: 16px
> Name: 15px / 16px - Bold #262626
> Margin between name and username: 4px
> Username: 15px / 16px - Regular #909399
> Date: 13px / 16px - Medium #45474D
> Margin between name and message: 4px
> Message: 17px / 24px - Regular #45474D

### PR DESCRIPTION
**Pull request by mltbnz**
fixes #48

### CODE REVIEW

**Comment by mltbnz** [comment]
Screenshot 2019-04-08 at 09 14 04

**Comment by mltbnz** [comment]
trying hard to get it right 💪  but I don't know what border you mean and to which text it should align... 
Also the font is medium already. Using the system font though

**Comment by zutrinken** [comment]
This border:

55705322-d30d8080-59de-11e9-9281-e2112a73d409

**Comment by mltbnz** [comment]
ah ha! That one. Gotcha
So in iOS that one is called a seperator. Caused some confusion but now I know

**Comment by zutrinken** [comment]
my bad 🙃 ... looks good now. Thanks!

**Pull request merged**
