### PR TITLE
Collect strings

### PR DESCRIPTION
**Pull request by mltbnz**
Intends to collect all NSLocalizedStrings in an extension to make them reusable and remove strings from logic controllers. Also moves and collects all URLs to the Constants container. 

* adds String+LocalizedStrings extension
* update strings in code with static lets from extension
* move URLs in Constants container
* change Constants type to enum so it is not instantiatable

🎨

### CODE REVIEW

**Comment by lennet** [comment]
Nice! Maybe we should think about using code generation like https://github.com/SwiftGen/SwiftGen to generate String+NSLocalizedStrings

**Comment by mltbnz** [comment]
Nice tool. Maybe we add https://github.com/JiriTrecak/Laurine to the app. For other use cases I don't know if we need to add a new dependecy to the project. But in general I don't know if adding another dependency is really needed for the ~ 30 Strings that are in the app.

**Comment by mltbnz** [comment]
Btw. do you think we should add `static func` for these things?
```swift
var title: String {
        return NSLocalizedString("rules.title.\(rawValue)", comment: "")
    }

    var text: String {
        return NSLocalizedString("rules.text.\(rawValue)", comment: "")
    }
```

**Comment by lennet** [comment]
> Nice tool. Maybe we add https://github.com/JiriTrecak/Laurine to the app. For other use cases I don't know if we need to add a new dependecy to the project. But in general I don't know if adding another dependency is really needed for the ~ 30 Strings that are in the app.

You are right, lets not introduce a dependency and re-evaluate this once maintaining this files becomes a lot of work

**Comment by lennet** [comment]
> Btw. do you think we should add `static func` for these things?
> 
> ```swift
> var title: String {
>         return NSLocalizedString("rules.title.\(rawValue)", comment: "")
>     }
> 
>     var text: String {
>         return NSLocalizedString("rules.text.\(rawValue)", comment: "")
>     }
> ```

I'm not sure. I first thought no because the current code is compact and nice. 

However updating Rules by changing the content or the order is currently a lot of work and requires changes in all localization files. I think moving away from that logic and define the order in codes makes it easier to maintain

**Comment by mltbnz** [comment]
So I just leave it like it is

**Pull request merged**
