### PR TITLE
Add image uploader

### LINKED ISSUE #10: A photouploader is missing
... to share pictures with the world :)

### PR DESCRIPTION
**Pull request by mltbnz**
So that this 5 years old issue ticket can finally be closed 😆

closes #10 

## 📝 Docs

- [ ] Did you update the [CHANGELOG.md](https://github.com/criticalmaps/criticalmaps-ios/blob/master/CHANGELOG.md)?

## 📲 What

A description of the change.

## 🤔 Why

Some background context on why the change is needed.

## 👀 See

Screenshots, external resources?
- [ ] Added snapshot tests (using iPhone 8 Simulator)

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

## ♿️ Accessibility 

- [ ] Tap targets use minimum of 44x44 pts dimensions
- [ ] Works with VoiceOver
- [ ] Supports Dynamic Type

### CODE REVIEW

**Comment by mltbnz** [comment]
I am actually unsure how this feature works?! 
Is it just uploading an image to `/gallery`? Can users on android also check the gasket at some point?

**Comment by cbalster** [comment]
On Android - after taking a picture - there's a confirmation dialog with a
thumbnail of the image before upload to the gallery.

**Comment by mltbnz** [comment]
> On Android - after taking a picture - there's a confirmation dialog with a thumbnail of the image before upload to the gallery.
> […](#)

Thanks. So after confirming the upload users can only see what they uploaded on the cm website, right?

**Comment by cbalster** [comment]
Exactly.

**Pull request closed without merging**
