### PR TITLE
Introduced Swift Packager Manager as a dependency manager

### PR DESCRIPTION
**Pull request by lennet**
I started replacing Cocoapods with Swift Packager Manger as it's build right into Xcode 11

Open Questions:
- [x] Swift format
- [x] License Plist generation

#113

### CODE REVIEW

**Comment by lennet** [comment]
Yes both work without cocoapods but I still need to do that 😅

**Comment by lennet** [comment]
bundled swift-format into the repo and removed all remaining cocoapods files. 
license-plist doesn't support SwiftPM [yet](https://github.com/mono0926/LicensePlist/issues/107)

**Comment by mltbnz** [comment]
LicensePlist should work now 🥳
https://github.com/mono0926/LicensePlist/releases/tag/2.6.0

**Comment by mltbnz** [comment]
Tried it yesterday and it seems like LicensePlist still has some issues...

Also to get rid of the `Pod` folder we should execute 
```shell
pod deintegrate
``` 

and also delete the `.xcworkspace`

**Comment by lennet** [comment]
I did that. The problem ist that many cocoapods files are part of our .gitignore file so they don't get automatically deleted. I removed them from our .gitignore to make the more visible. After deleting the files LicensePlist works for me

**Comment by mltbnz** [comment]
Works. Nice.
But now I have this https://github.com/mono0926/LicensePlist/issues/105

**Comment by lennet** [comment]
It seems to be unrelated to this PR as the bug is already in master. I think create an issue and a follow up PR once we have a fix

**Comment by mltbnz** [comment]
Ok. Then merge at will

**Pull request merged**
