### PR TITLE
Use GitHub Actions instead of Travis

### PR DESCRIPTION
**Pull request by fbernutz**
Use [GitHub Actions](https://github.com/features/actions) instead of Travis. GitHub Actions are directly integrated in GitHub and are significantly faster. 

### Travis

Travis took ~13 min in total with queueing (the jobs ran for about 4-5 min).

Screen Shot 2020-01-11 at 12 32 39

### GitHub Actions

GitHub Actions take ~3-4 min in total. 🚀

### CODE REVIEW

**Comment by mltbnz** [comment]
This is cool!
Does it make sense to pin the Xcode and macOS version the CI is running on? Do you know what does GitHub actions pick if it is not set?

**Comment by fbernutz** [comment]
> This is cool!
> Does it make sense to pin the Xcode and macOS version the CI is running on? Do you know what does GitHub actions pick if it is not set?

Yes, this makes sense! Currently when using `macOS-lastest` there is Xcode 11.2.1 set as default ([more information](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015)). I'll try to make it explicit, so we still have a green pipeline after an Xcode Update or macOS Update.

**Comment by fbernutz** [comment]
✅ Pinned Xcode Version to 11.3
❌ Not pinned macOS Version (it's not possible, there is only `macOS_latest` tag and we are depending on GitHubs update mechanisms) 

There is something like [self hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners) we _could_ try out, but only if we have problems with the CI, I think.

**Comment by lennet** [comment]
Wow this is great! I did not try it myself but maybe this might help to specify a Xcode version https://www.jessesquires.com/blog/selecting-an-xcode-version-on-github-ci/

**Comment by fbernutz** [comment]
> Wow this is great! I did not try it myself but maybe this might help to specify a Xcode version https://www.jessesquires.com/blog/selecting-an-xcode-version-on-github-ci/

I already used the env "workaround" to pin the Xcode Version 🙂

**Comment by stephanlindauer** [comment]
nice! just one quick comment: with github actions we get  2,000 minutes of building stuff on their infrastructure for free. if we exceed, we won't be able to build anymore for that month. now with 4 minutes per build that would be 500 hundred free builds per month. currently there's a lot of head room but we don't know if we might exceed this limit eventually. therefore: would it make sense to keep the travis config in the project?

**Comment by fbernutz** [comment]
Maybe I misunderstood the documentation about the pricing, but I thought Github Actions is completely free for public repositories. 
https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions

**Pull request merged**
