### PR TITLE
Translation of Localizable.strings in French

### PR DESCRIPTION
**Pull request by AlbanSagouis**
Hi,
This is my first Pull request, sorry if I made anything wrong. I have no idea how to test the modifications I made but let me know if I can help.
Cheers,
Alban

### CODE REVIEW

**Comment by lennet** [comment]
Merci beacoup! This is awesome! 

If you have a Mac with Xcode Installed, you can test the localization by Adding it to the project here:

Bildschirmfoto 2019-05-03 um 18 26 43

Here are some screenshots of the App running in French:

Bildschirmfoto 2019-05-03 um 18 21 50
Bildschirmfoto 2019-05-03 um 18 21 56
Bildschirmfoto 2019-05-03 um 18 22 17

I think you forgot to localize `settings.opensource.title` but the rest looks great!

**Comment by AlbanSagouis** [comment]
Great! Glad it helped and that it does not look too bad (French is often longer than English and I have a small iPhone SE).
I corrected a typo and added the translation that was missing and committed but I believe I committed to my fork and not your original project. I guess I should have contacted you before requesting a pull and we could have discussed about it right?


I have a Windows PC and Notepad++ is the most programming oriented tool I have...

**Comment by cbalster** [comment]
@AlbanSagouis 
First of all thank you very much!
When you add a commit to a branch that you already have a pull request for, it is automatically added to the existing pull request - so everything is fine!

**Comment by cbalster** [comment]
Oh, and maybe if you want to and have the time, feel free to take a look at the french translations for the android version of the app. We already have a french translation but it is quite old and therefore missing quite a lot of strings. We are using transifex for the android translations: https://www.transifex.com/criticalmaps/criticalmaps/

**Comment by lennet** [comment]
Let's merge it and ship it with next release 🎉 I'll create a follow up PR for the project configuration

**Pull request merged**
