### PR TITLE
Added options for appearance settings (#182)

### PR DESCRIPTION
**Pull request by Freelenzer**
## 📝 Docs

- [x] Did you update the [CHANGELOG.md](https://github.com/criticalmaps/criticalmaps-ios/blob/master/CHANGELOG.md)?

## 📲 What

Added an implementation of https://github.com/criticalmaps/criticalmaps-ios/issues/182
It enables the user to set if he wants to use system appearance settings or dark/light mode only.
On iOS < 13 the option is a switch.

## 🤔 Why

Users can customise their appearance. Default is system so the app 
But it also gives the users the option to quickly change e.g. from dark to light mode so he can see the map better if he is in light environment.

## 👀 See

Screenshots, external resources?
- [x] Added snapshot tests (using iPhone 8 Simulator)

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

## ♿️ Accessibility 

- [x] Tap targets use minimum of 44x44 pts dimensions
- [x] Works with VoiceOver
- [x] Supports Dynamic Type

### CODE REVIEW

**Review by fbernutz — COMMENTED** [review]
Thanks for the contribution 🎉 
I just tested your implementation and it works perfectly for < iOS 13 and for >= iOS 13. Good job! 
Currently the snapshot tests fail in CI because we still use Xcode 11.5 and therefore iOS 13.7 in the CI. I added an issue for that, so we run tests in CI with iOS 14. https://github.com/criticalmaps/criticalmaps-ios/issues/337 
Until this is resolved, could you record the tests again with an iOS 13 simulator? Then it should be all green and we could merge this.

**Comment by Freelenzer** [comment]
ok got it :)
Everything green now.

**Review by fbernutz — APPROVED** [review]

**Comment by zutrinken** [comment]
Hey @Freelenzer thanks so much for your PR. I Finally had the time to check it out and found an issue that might relate to this. Maybe you wanna check it out: #379

**Comment by fbernutz** [comment]
Just fixed with #380

**Pull request merged**
