### PR TITLE
Rebuild of the app

### PR DESCRIPTION
**Pull request by mltbnz**
## 📝 Docs

- [x] Did you update the [CHANGELOG.md](https://github.com/criticalmaps/criticalmaps-ios/blob/master/CHANGELOG.md)?

## 📲 What

This is essentially a rebuild of the App built with [`The Composable Architecture`](https://github.com/pointfreeco/swift-composable-architecture) and `SwiftUI`. The project consists of a Swift package which bundles the individual modules for the app. Building the app in modules allows to work on features without building the entire application, which improves compile times and SwiftUI preview stability. Also every feature is its own target which makes it also possible to build mini-apps to run in the simulator for preview.

_Missing_
The Friends feature is currently missing.
 

## 🤔 Why

Maintaining the codebase became a bit hard and since I decided I wanted to keep maintaining the project I wanted a codebase which is both maintainable and modern to work on. There are a lot of benefits as well: 

- uniform feature architecture  
- high testability
- modularisation
- enables easy porting to other platforms
- managing dependencies and side effects in an understandable way

## 👀 See

Screenshots, external resources?
- [x] Added snapshot tests

Screenshot 2021-12-30 at 11 41 51
Screenshot 2021-12-30 at 11 38 35
Screenshot 2021-12-30 at 11 38 30
Screenshot 2021-12-30 at 11 37 59
Screenshot 2021-12-30 at 11 38 07
Screenshot 2021-12-30 at 11 38 26
Screenshot 2021-12-30 at 11 38 24
Screenshot 2021-12-30 at 11 38 18
Screenshot 2021-12-30 at 11 38 15

## ♿️ Accessibility 

- [x] Tap targets use minimum of 44x44 pts dimensions
- [x] Works with VoiceOver
- [x] Supports Dynamic Type 

## 🔄 Review & Merge

This PR will replace all files on `main` and therefore needs to be merged forcefully. I preserved the current state of the app on the branch [`release/3.9.2`](https://github.com/criticalmaps/criticalmaps-ios/tree/release/3.9.2)  to keep around.
Review of the code is optional but I would like you to check out the branch, launch the so the see if anything pops out that needs fixing. Before a potential release I would also like to do a new version for Testflight and maybe a tweet so we might get some people to test this rebuild.

### CODE REVIEW

**Comment by fbernutz** [comment]
Hey @mltbnz! 
Amazing job with the rewrite! 👏

I just had a look at it (finally) and here's some small feedback:
- The failing test `AppNavigationViewSnapshotTests.test_appNavigationView_WithBadge()` in the CI fails locally for me as well when I run with Xcode 13.2.1 and iPhone 8 Plus with latest iOS, maybe it's because of the precision of 95%? 
- The switch for the observation mode in settings can't be activated with voice over 🤔 
- All elements of a tweet are accessible on their own, so navigating with voice over is a bit hard on the list. Maybe we can group the elements similar to the old/current version?
- Maybe we can switch from `HStack` to `VStack` for the `TweetView` when the user is using an accessibilitySize? 
- The `GuideDetailView` needs to have a `ScrollView` for larger font sizes, otherwise text will be truncated.

I think all of these issues can be fixed in a later version as well. The rest looks really great already! ✨ Thumbs up from me! 

Some screenshots: 
| 1 | 2 | 3 | 4 |
|---|---|---|---|
|Screen Shot 2022-01-02 at 09 38 20|Simulator Screen Shot - iPhone 8 - 2022-01-02 at 09 33 14|Simulator Screen Shot - iPhone 8 - 2022-01-02 at 09 37 19|Simulator Screen Shot - iPhone 8 - 2022-01-02 at 09 33 25|

**Comment by mltbnz** [comment]
Thanks. The points should be fixed easily so I'll address them in this PR.

The failing test is currently a bit of a mystery. Don't get why these are different on the CI run. I recorded the Snapshots with an iPhone 12 btw. I'll update the PR template. 

The toggle action hopefully is just an `accessibilityAction` modifier 😄

**Comment by fbernutz** [comment]
Mhmmm that's weird, the test even fails on iPhone 12 for me on my machine.

**Comment by mltbnz** [comment]
Ok. Then I should double check it again if what I have checked in is even valid 🙈

**Comment by mltbnz** [comment]
seems like my update snapshot fixed it 🎉 
I addressed the issues. Thanks for taking the time to check it out.

Do you have an idea what would be the best way to merge it back to `main`?

**Comment by fbernutz** [comment]
@mltbnz Amazing! 

Not sure if this is the easiest way but I would go with this:
- on `develop` branch: merge in the main branch with ["ours" merge strategy](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours), `git merge -s ours main` for solving the conflicts 
- from Github UI or locally on `main` branch: do a merge commit or squashed commit to merge `develop` into `main`

**Pull request merged**
